use_frameworks!

target 'Swifthereum_Example' do
    platform :ios, '11.0'
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for GethTest
    # pod 'Swifthereum', :path => '../' # files are added manually to the project
    pod 'Geth', '~> 1.7.2'
    pod 'BigInt', '~> 3.0'

  target 'Swifthereum_Tests' do
    inherit! :search_paths

    
  end
end
